### ISSUE TITLE
Consider using mobile-device-detect package for detection of mobile, iphone, ipad ets

### ISSUE THREAD

**Issue by phpb-com** [shiyiya/oplayer#10]
Hi again, I wanted to see what were your thoughts on using https://github.com/duskload/mobile-device-detect to detect different types of devices, instead of rolling your own. I can probably try and create a PR if you do not mind, otherwise I'll close the issue. Thanks.

**Comment by shiyiya** [comment]
It is important to keep the project as clean as possible and avoid unnecessary dependencies. Most of the features in there are not used either, so I don't think this dependency is needed at the moment, at least not right now, what do you think, or are you running into any problems?

**Comment by shiyiya** [comment]
- Does it not work on Smart TV now?

- PR welcome.

**Comment by shiyiya** [comment]
Maybe the webview is too old.
You can refer to https://github.com/shiyiya/oplayer/tree/main/packages/hls

**Comment by shiyiya** [comment]
Before PR, you need to create a new branch, do not make changes in the master branch, make sure the master branch on the commit of the clear, or there will be a lot of **merge commit**.

**Comment by shiyiya** [comment]
Let me know if you need any help 😄

**Comment by shiyiya** [comment]
The next version uses await , run the website before updating to see if it is working properly.
