### ISSUE TITLE
Recommended to give each element a unique name to avoid custom styling errors caused by updated versions.

### ISSUE THREAD

**Issue by eritpchy** [shiyiya/oplayer#100]
## 🚀 Feature Proposal

Recommended to give each element a unique name to avoid custom styling errors caused by updated versions.

## Motivation

<img width="223" alt="image" src="https://github.com/shiyiya/oplayer/assets/8630635/3a2d301e-d111-4d60-a02c-f8069bf50340">

$('.css-s9s35s') ???
so ugly...

## Example

<img width="323" alt="image" src="https://github.com/shiyiya/oplayer/assets/8630635/b218f6ea-1bbe-416c-8678-d4fe62defd3f">

$('#oplayer-icon-settings')
😍😍😍

## Pitch

Why does this feature belong in the oplayer ecosystem?

**Comment by shiyiya** [comment]
For style isolation, subsequent updates that do not involve styles will not change the hash value

**Comment by eritpchy** [comment]
<img width="959" alt="image" src="https://github.com/shiyiya/oplayer/assets/8630635/bfc586b3-2fbc-4f81-93dd-c298e555bf7c">
<img width="338" alt="image" src="https://github.com/shiyiya/oplayer/assets/8630635/b169e661-9a47-487b-9b0b-3ace505ea2be">

For example: what if.. you fix controlBarTitle margin error,  css hash value will changed?

**Comment by shiyiya** [comment]
只能做取舍，有弊端也有好处，欢迎pr，最近没空了

**Comment by eritpchy** [comment]
好的吧👌

**Comment by shiyiya** [comment]
> <img alt="image" width="959" src="https://user-images.githubusercontent.com/8630635/275383767-bfc586b3-2fbc-4f81-93dd-c298e555bf7c.png"> <img alt="image" width="338" src="https://user-images.githubusercontent.com/8630635/275384920-b169e661-9a47-487b-9b0b-3ace505ea2be.png">
> For example: what if.. you fix controlBarTitle margin error, css hash value will changed?

fixed.
