### ISSUE TITLE
Is there any option in Player to update Playlist array

### ISSUE THREAD

**Issue by MuhammadTufailAli** [shiyiya/oplayer#101]
I am using Oplayer to display playlist. I have my fav channels in it and when i click on my fav button then my array length is increased for example before my channels array was 10 and after liking one channel it becomes 11. Now i want to update my playlist how can i do this.
This there any way in Oplyaer to do this.

**Comment by shiyiya** [comment]
player.context.playlist.changeSource([])
// will replay list from index i think

**Comment by MuhammadTufailAli** [comment]
Let me try this

**Comment by MuhammadTufailAli** [comment]
How i am going to use it can you please give me an example 
i have array in variable called newSources

**Comment by shiyiya** [comment]
player.context.playlist.changeSourceList(sources)

**Comment by MuhammadTufailAli** [comment]
When i did it i got Following
![sssss](https://github.com/shiyiya/oplayer/assets/80455451/1aeaadab-a9a2-4871-a177-f4eaf5de3b1c)

**Comment by shiyiya** [comment]
code？

**Comment by MuhammadTufailAli** [comment]
For testing purpose i am changing list when i click on next button
My code
 const newSources = AllChannelsinonearray.slice(1);
          

              newplayer.context.playlist.changeSourceList(newSources);
              i am doing this

**Comment by MuhammadTufailAli** [comment]
is it possible that playlist change without reload

**Comment by shiyiya** [comment]
may be newsource format error.

**Comment by shiyiya** [comment]
Next time, please use the template to create an issue

**Comment by MuhammadTufailAli** [comment]
Format is same i am using 
AllChannelsinonearray when i am first creating player playlist
and when i click next button i just slice one element from it and do this
const newSources = AllChannelsinonearray.slice(1);
newplayer.context.playlist.changeSourceList(newSources);

**Comment by shiyiya** [comment]
no, changesourcelist(list)
list just `[{
  src?: string
  duration?: string
  subtitles?: SubtitleSource[]
  thumbnails?: Thumbnails
  highlights?: Highlight[]
}]`
