### ISSUE TITLE
Is there any way to Change currentIndex of playlist

### ISSUE THREAD

**Issue by MuhammadTufailAli** [shiyiya/oplayer#105]
I am using Oplayer and using playlist in it. 
When i change channel and if the channel does not play then currentIndex Disappers. I want to chnage currentIndex manually is there any way to do this.

If channel play.
![image](https://github.com/shiyiya/oplayer/assets/80455451/30baab79-4bf0-48b1-8f8e-70913f59d12d)

If channel does not play.
![image](https://github.com/shiyiya/oplayer/assets/80455451/148ec8b6-b6df-46b6-8f94-2398dfbf34fb)

**Comment by MuhammadTufailAli** [comment]
Sorry if channel plays currentIndex appers
![image](https://github.com/shiyiya/oplayer/assets/80455451/558155e1-5f6b-4501-bd51-4abaf4bcb871)

**Comment by shiyiya** [comment]
```js 
player.context.playlist.changeSourceList(number)
```

**Comment by MuhammadTufailAli** [comment]
Thanks it is working Fine

**Comment by MuhammadTufailAli** [comment]
I have one more question
newplayer.on("loadedmetadata", () => {
              setSelectedChannelNumberWhichWillChange((last) => {
                return DynamicChannel + 1;
              });

              // localStorage.setItem(
              //   "EpisodeNumberThatWillChange",
              //   JSON.stringify(DynamicChannel + 1)
              // );
            });
            
            This function is used to know it the data is load 
            Is there any function which is opposite to it which is triggred when data failed to load?

**Comment by shiyiya** [comment]
on 'error'
