### ISSUE TITLE
Help me to integrate this player in react app with multi quality and multi audio support 

### ISSUE THREAD

**Issue by anuragpindoriya** [shiyiya/oplayer#107]
## 💬 Questions and Help

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

and i try my source in demo player but after set source it give me error source not support but source fully working ( HLS source )

Try if you wanna test :-  https://pastebin.com/F3i3JdSm

**Comment by shiyiya** [comment]
![IMG_1816](https://github.com/shiyiya/oplayer/assets/34017352/8be49df4-a2ca-48e7-b36c-da3054ef7557)

**Comment by anuragpindoriya** [comment]
![Screenshot_20231118_001325_Chrome.jpg](https://github.com/shiyiya/oplayer/assets/77160230/110e5796-8722-4948-9824-7791200bb7be)

I face this error 😅😅

**Comment by shiyiya** [comment]
hls support.
set format =hls

**Comment by anuragpindoriya** [comment]
> hls support. set format =hls

Can you give me a code snippet for react i try understand documenting but all are mix which plugging use, what is boiler plate code in react little bit Massey

**Comment by anuragpindoriya** [comment]
> ![IMG_1816](https://github.com/shiyiya/oplayer/assets/34017352/8be49df4-a2ca-48e7-b36c-da3054ef7557)
> 

Try in PC very strange behavior ( in mobile working but in pc not working 🤣🤣 )
