### ISSUE TITLE
Chromecast is functioning with certain videos but encountering issues with others.

### ISSUE THREAD

**Issue by MuhammadTufailAli** [shiyiya/oplayer#111]
Environment

"@oplayer/core": "^1.2.31",
    "@oplayer/danmaku": "^1.2.23",
    "@oplayer/dash": "^1.2.22",
    "@oplayer/hls": "^1.2.22",
    "@oplayer/mpegts": "^1.2.22",
    "@oplayer/plugins": "^1.0.7",
    "@oplayer/react": "^1.2.8",
    "@oplayer/torrent": "^1.2.23",
    "@oplayer/ui": "^1.2.32",
      browser: chrome 

 Bug Report

I am using Oplayer and using chromecast in it
Chromecast is working perfectly fine but on some movies chromecast is not playing
.Chromcast get connected with tv and it shows the icon of chromecast on it and the movie is not played why this is happening and how can i detect it.
I also used the movie link and played it on vlc and cast it on tv it work absolutely fine there.
I am also adding video recording.

https://github.com/shiyiya/oplayer/assets/80455451/6744e24a-1b76-4a85-bb02-29abc0bfa613

**Comment by MuhammadTufailAli** [comment]
In Case video is not playing i am also adding screenshot.
![Uploading WhatsApp Image 2023-12-26 at 11.36.27_241dab
![WhatsApp Image 2023-12-26 at 11 36 28_b4f6aafb](https://github.com/shiyiya/oplayer/assets/80455451/ac6db0f0-dfd3-4d8e-ac0d-9c03a0b30e52)
15.jpg…]()


https://github.com/shiyiya/oplayer/assets/80455451/2438d9bb-435f-4b9c-9851-0bf698d358b8

**Comment by MuhammadTufailAli** [comment]
In case video is not playing i am also attaching screenshots
![WhatsApp Image 2023-12-26 at 11 36 27_241dab15](https://github.com/shiyiya/oplayer/assets/80455451/f5d8fbb6-db2c-4a4b-97f9-ef8ffa98c36b)
![WhatsApp Image 2023-12-26 at 11 36 28_b4f6aafb](https://github.com/shiyiya/oplayer/assets/80455451/d98a33ef-e309-47a2-8e5c-08a022709cc8)

https://github.com/shiyiya/oplayer/assets/80455451/e1cd1e20-af50-4553-adbd-9e2597733629

**Comment by shiyiya** [comment]
could u try on https://oplayer-git-refactor-chromecast-shiyiya.vercel.app/player ?
