### ISSUE TITLE
Scrubbing on the seek handle works intermittently on android chrome

### ISSUE THREAD

**Issue by evmatic** [shiyiya/oplayer#118]
The seek handle is not draggable sometimes on android, though it works out well as expected in iOS safari. When we try to drag the seek handle to and fro, it feels like it got locked out and will not move at all and occurs intermittently.

**Comment by shiyiya** [comment]
The seekbar on the phone is relatively small and may be difficult to touch

**Comment by evmatic** [comment]
Hello,
the issues is occurring rampantly, only on mobile browser in android, tested only in chrome, safari in iOS is working flawlessly.
To reproduce, play any videos on mobile chrome browser on android, and try to drag the seekbar, if it works for the first time, wait for a bit and try dragging to and fro again, repeat 2-4 times.

**Comment by shiyiya** [comment]
Try https://onime.netlify.app/v/3724 

How'd it go?

**Comment by evmatic** [comment]
http://139.162.61.196/demo.html

Please try to move the seeker 2,3,4 times, often times, it becomes undraggable.
