### ISSUE TITLE
Image placement holder for broken images in the playlist items

### ISSUE THREAD

**Issue by evmatic** [shiyiya/oplayer#120]
It will be really nice to have an image place holder (or an onerror event to hook to for images not loaded) for items in the playlist where the poster images are dead or broken.
<img width="826" alt="Screenshot 2024-03-21 at 3 40 01 PM" src="https://github.com/shiyiya/oplayer/assets/163381794/5403d480-c676-414f-830b-6ab7f8398e61">

**Comment by shiyiya** [comment]
fixed. @1.0.11-alpha.1
