### ISSUE TITLE
Chromecast plugins error

### ISSUE THREAD

**Issue by evmatic** [shiyiya/oplayer#123]
`chromecast.min.js?v=1.0.12-beta.3:8 Uncaught TypeError: Cannot read properties of undefined (reading 'isIOS')
    at d.canPlay (chromecast.min.js?v=1.0.12-beta.3:8:1480)
    at d.apply (chromecast.min.js?v=1.0.12-beta.3:8:913)
    at e.applyPlugin (index.ui.js?v=1.2.34-beta.1:8:11238)
    at Array.forEach (<anonymous>)
    at e.create (index.ui.js?v=1.2.34-beta.1:8:9089)`

The error above is seen in the latest beta in chrome browser, crashing the whole player!

**Comment by shiyiya** [comment]
check https://github.com/shiyiya/oplayer/blob/f33c6543bda5734e48dd9f4a35f323dbeabd3328/packages/docs/public/ohls.html#L216


it is working

**Comment by evmatic** [comment]
Hello,
the error occurs only on site loaded on a local network like http://192.168.0.....
The first time it works, but after reloading and getting the NO_DEVICE_AVAILABLE error, the player breaks down completely.

`canPlay() {
            return o && !a.isIOS
        }`

This line of code in chrome cast extension, `a` seems to be undefined.

**Comment by shiyiya** [comment]
debugger，what is a？

**Comment by shiyiya** [comment]
or try use index.min.js

**Comment by evmatic** [comment]
Its a weird situation, hosting the chromecast extension js on the remote server instead of using the distributed cdn makes the problem goes away. Maybe, cdn server is restricting content access from origin with 192.168.0.....

**Comment by shiyiya** [comment]
You're talking about a strange phenomenon. It's not like it's fine the first time and then breaks down again.
