### ISSUE TITLE
Question about oplayer 

### ISSUE THREAD

**Issue by yektamovie** [shiyiya/oplayer#131]
Hello, this is my video player: 
`OPlayer.make('#oplayer', {
                                    pictureInPicture: true,autoplay: true,
                                    controller:{slideToSeek: 'long-touch'},
                                    source: {
                                        src: '',
                                        poster: ''
                                    }
                                })
                                .use([OUI({
                                    pictureInPicture: true,autoplay:true,controller:{slideToSeek: 'long-touch'}}), ODash()])
                                .create();
                        }`

How can I enable slideToSeek?

 And how to move the settings icon above the video?

 If anyone knows, tell me or edit my script

 Thanks

**Comment by shiyiya** [comment]
https://github.com/shiyiya/oplayer/blob/a6f564d185d46974885c20fcfd8ca90a8d9a477f/examples/standalone/main.ts#L79

**Comment by yektamovie** [comment]
> https://github.com/shiyiya/oplayer/blob/a6f564d185d46974885c20fcfd8ca90a8d9a477f/examples/standalone/main.ts#L79

It's not working.
All script:
<script src="http://cdn.dashjs.org/latest/dash.all.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/npm/@oplayer/dash@latest/dist/index.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/npm/@oplayer/core@latest/dist/index.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/npm/@oplayer/ui@latest/dist/index.min.js"></script>
                    <div id="oplayer" style="width:100%;height:auto;margin-top: -20%;"></div>
 <script>
OPlayer.make('#oplayer', {
        pictureInPicture: true,
        autoplay: true,
        source: {
            src: '<?php echo $dash; ?>',
            poster: '<?php echo $poster; ?>'
        },
        controller: {
          setting: 'auto',
          display: 'always',
          coverButton: true,
          displayBehavior: 'hover',
          header: { back: 'always' },
          slideToSeek: 'always'
        
      },
    })
    .use([OUI({controller: {
          setting: 'auto',
          display: 'always',
          coverButton: true,
          displayBehavior: 'hover',
          header: { back: 'always' },
          slideToSeek: 'always'
        }
      }), ODash()])
    .create();
}
</script>

**Comment by shiyiya** [comment]
https://github.com/shiyiya/oplayer/blob/a6f564d185d46974885c20fcfd8ca90a8d9a477f/packages/docs/public/oplayer.js#L93

script demo here

**Comment by yektamovie** [comment]
> https://github.com/shiyiya/oplayer/blob/a6f564d185d46974885c20fcfd8ca90a8d9a477f/packages/docs/public/oplayer.js#L93
> 
> script demo here

Tanks for help (🇮🇷my fiend🤝)

**Comment by shiyiya** [comment]
``
