### ISSUE TITLE
Add subtitle to /packages/docs/public/oplayer.js

### ISSUE THREAD

**Issue by yektamovie** [shiyiya/oplayer#132]
How to add subtitles to your demo code?
** **
[/packages/docs/public/oplayer.js](https://github.com/shiyiya/oplayer/blob/a6f564d185d46974885c20fcfd8ca90a8d9a477f/packages/docs/public/oplayer.js)

**Comment by shiyiya** [comment]
oplayer.vercel.app/oplayer?src=xxx.mp4&subtitle=xxx.srt

**Comment by yektamovie** [comment]
There is no way to do this without ?get= ? Inside the code itself?

**Comment by shiyiya** [comment]
You can, but you need to write the code yourself, not here
