### ISSUE TITLE
subtitle stuck problem

### ISSUE THREAD

**Issue by meganek31** [shiyiya/oplayer#136]
## Environment

- oplayer/core:   // 1.2.36
- oplayer/ui:       // 1.3.3-beta.8
- oplayer/hls:    // latest
- oplayer/dash:    // version
- platform:          // Windows
- browser:           // chrome 128.0.0.0
## 🐛 Bug Report

play a video with subtitles, then move the duration of the video to the middle, you will see that there is a problem with the subtitles, a subtitle text is constantly stuck, new subtitles appear under that text

## Expected behavior

Expired subtitles should disappear.

## Link to repl or repo (highly encouraged)

https://github.com/meganek31/oplayer-bugs/blob/main/bug.js
https://github.com/meganek31/oplayer-bugs/blob/main/eng%20(2).srt

**Comment by shiyiya** [comment]
Uploading 录屏2024-09-06 09.48.11.mov…

**Comment by shiyiya** [comment]
![image](https://github.com/user-attachments/assets/4d4a937e-cf56-4e62-83f0-f1a83c7e1280)

I don't know why you're showing an error, the code doesn't even set shubtitle correctly

**Comment by meganek31** [comment]
```
$json_data2 = [];
        foreach ($subtitles as $subtitle) {
            $subs_item = [
              'src' => $subtitle['url'],
              'name' => $subtitle['name'],
              'offset' => '2',
            ];
            if ($subtitle['name'] == 'English') {
              $subs_item['default'] = true;
            }
            $json_data2[] = $subs_item;
        }

        $json_output2 = json_encode($json_data2, JSON_PRETTY_PRINT);
```
        
        I get subtitles from my sql table with this php code
        
        ```
OUI({
	subtitle: {
		source: [{
			"src": "https:\/\/video.playerflare.xyz\/the-witcher-75\/2\/1\/English.srt",
			"name": "English",
			"offset": "2",
			"default": true
		}],
	},
})
```

the result is this js code
