### ISSUE TITLE
Change subtitle programmatically

### ISSUE THREAD

**Issue by NADESHIKON** [shiyiya/oplayer#17]
Is it possible to change subtitles programmatically by calling the methods inside the player instance? Since it looks like the subtitle option is inside UI plugin.

**Comment by shiyiya** [comment]
```ts
player.emit('subtitlechange',{} as Subtitle[])
```

**Comment by NADESHIKON** [comment]
> ```ts
> player.emit('subtitlechange',{} as Subtitle[])
> ```

Thanks, is it also possible to adjust the subtitle text size, right now it looks extremely small (like 3px)

**Comment by shiyiya** [comment]
Provide fontSize value to change font size

```ts
export type Subtitle = {
  source: SubtitleSource[]
  fontSize?: number
  enabled?: boolean
}
```

**Comment by shiyiya** [comment]
The font size cannot be changed on IOS using the built-in caption.

**Comment by NADESHIKON** [comment]
Looks like this does not set the subtitles, it doesn't get displayed.
