### ISSUE TITLE
HLS quality selection

### ISSUE THREAD

**Issue by NADESHIKON** [shiyiya/oplayer#18]
Is it possible to implement HLS quality selection similar to how Artplayer did it in https://github.com/zhw2590582/ArtPlayer/issues/253#issuecomment-1108458428

**Comment by shiyiya** [comment]
79cfe36419c4b9742b475e6c4c914ecaff293f62

**Comment by NADESHIKON** [comment]
> Done ✅

Thank you, mind publishing a release?

**Comment by shiyiya** [comment]
v.0.31

**Comment by NADESHIKON** [comment]
@shiyiya Looks like the quality selection is still rather off. Only "Auto" is available even it's not supposed to since m3u8 has multiple qualities
![image](https://user-images.githubusercontent.com/20222292/189058173-edee1c8b-ddb2-44d2-abad-f31a9533c4b5.png)

**Comment by shiyiya** [comment]
provide url

**Comment by shiyiya** [comment]
![image](https://user-images.githubusercontent.com/34017352/189066310-a508c739-5155-4677-95b6-aaa394bb10a0.png)

https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8

**Comment by shiyiya** [comment]
Try running your url on the official hlsjs demo to see if level is supported

**Comment by NADESHIKON** [comment]
> Try running your url on the official hlsjs demo to see if level is supported

![image](https://user-images.githubusercontent.com/20222292/189066933-d973bc4a-e432-4ebf-b06e-f2b999a23f46.png)

Looks like they are supported. I could properly get all the levels with example provided in https://github.com/zhw2590582/ArtPlayer/issues/253#issuecomment-1108458428

**Comment by shiyiya** [comment]
Close this issue if it meets expectations

**Comment by shiyiya** [comment]
> Testing https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 on my site (just replacing the video URL, shows the quality levels, but the same problem with no quality menu if not refreshed. This is with Remix SSR code.


Latest submission not yet released.

**Comment by shiyiya** [comment]
Run the latest (unreleased) code according to [this](https://github.com/shiyiya/oplayer/blob/main/CONTRIBUTING.md).

**Comment by NADESHIKON** [comment]
> 

Yes with this test url it does have levels. with 1.0.31 it also shows levels but I don't know if the URL I provided has anything more than Auto

**Comment by shiyiya** [comment]
> > 
> 
> Yes with this test url it does have levels. with 1.0.31 it also shows levels but I don't know if the URL I provided has anything more than Auto

I tested your url on the latest code and works as expected

**Comment by NADESHIKON** [comment]
> > > 
> > 
> > 
> > Yes with this test url it does have levels. with 1.0.31 it also shows levels but I don't know if the URL I provided has anything more than Auto
> 
> I tested your url on the latest code and works as expected

Yes, just ran locally and it does have levels now.

**Comment by shiyiya** [comment]
https://github.com/shiyiya/oplayer/commit/58fe2a4030aea8e224e43048b4679fbd6bdde91e#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33

Which one should I use as the name of the option if I don't have a name? This doesn't seem to be the right one at the moment？

**Comment by NADESHIKON** [comment]
> [58fe2a4#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33](https://github.com/shiyiya/oplayer/commit/58fe2a4030aea8e224e43048b4679fbd6bdde91e#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33)
> 
> Which one should I use as the name of the option if I don't have a name? This doesn't seem to be the right one at the moment？

It level name doesn't exist it's auto I think

**Comment by NADESHIKON** [comment]
> I need to go work on something else, PR welcome.

Alright

**Comment by NADESHIKON** [comment]
> > I need to go work on something else, PR welcome.
> 
> Alright

Can you publish a release

**Comment by shiyiya** [comment]
> > [58fe2a4#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33](https://github.com/shiyiya/oplayer/commit/58fe2a4030aea8e224e43048b4679fbd6bdde91e#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33)
> > Which one should I use as the name of the option if I don't have a name? This doesn't seem to be the right one at the moment？
> 
> It level name doesn't exist it's auto I think

I tested the url you provided, all levels have no names, there should not be so many auto

**Comment by NADESHIKON** [comment]
> > > [58fe2a4#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33](https://github.com/shiyiya/oplayer/commit/58fe2a4030aea8e224e43048b4679fbd6bdde91e#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33)
> > > Which one should I use as the name of the option if I don't have a name? This doesn't seem to be the right one at the moment？
> > 
> > 
> > It level name doesn't exist it's auto I think
> 
> I tested the url you provided, all levels have no names, there should not be so many auto

I tested my URL locally and they're displaying levels fine

**Comment by NADESHIKON** [comment]
![image](https://user-images.githubusercontent.com/20222292/189071847-07ee17ab-91e6-4b79-95bc-3bba72b78bb7.png)

**Comment by shiyiya** [comment]
https://github.com/shiyiya/oplayer/commit/58fe2a4030aea8e224e43048b4679fbd6bdde91e#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33

But the name may be wrong, check this commit

**Comment by NADESHIKON** [comment]
> [58fe2a4#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33](https://github.com/shiyiya/oplayer/commit/58fe2a4030aea8e224e43048b4679fbd6bdde91e#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR33)
> 
> But the name may be wrong, check this commit

I think only height should be considered so if level is -1 it's auto and for everything else just use height + P

**Comment by shiyiya** [comment]
it used height fallback, is right？

**Comment by NADESHIKON** [comment]
> it used height fallback, is right？

height is always present unless auto (-1)

**Comment by shiyiya** [comment]
if is 9/16 ?

**Comment by shiyiya** [comment]
Like the video on tiktok, the height is bigger than the width?

Or maybe the height is not the height of the video, but something else

**Comment by NADESHIKON** [comment]
> Like the video on tiktok, the height is bigger than the width?
> 
> Or maybe the height is not the height of the video, but something else

height is not the height of video, but rather resolution. hls.js named it differenlty

**Comment by shiyiya** [comment]
@phpb-com  ok, p
@NADESHIKON 👍 

I will release new version.

**Comment by shiyiya** [comment]
Create tags whenever you want. I'll create them all at once when I have time.

**Comment by shiyiya** [comment]
need m3u8 http url

**Comment by shiyiya** [comment]
> > it used height fallback, is right？
> 
> height is always present unless auto (-1)

got zero?
https://test-streams.mux.dev/x36xhzz/url_0/193039199_mp4_h264_aac_hd_7.m3u8
![image](https://user-images.githubusercontent.com/34017352/189077319-45fa80d7-c826-4397-b935-e6cbed4681df.png)

**Comment by shiyiya** [comment]
> @shiyiya试试这个网址https://cdn.fshck.com/HAH/playlist.m3u8

net::ERR_CONNECTION_REFUSED

**Comment by NADESHIKON** [comment]
> > @shiyiya try this URL https://cdn.fshck.com/HAH/playlist.m3u8
> 
> net::ERR_CONNECTION_REFUSED

CCP blocked this site, try with VPN if you're in china

**Comment by shiyiya** [comment]
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>2FHAH/2Fplaylist.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==</Key>
<BucketName>fishcake-mediadelivery</BucketName>
<Resource>/2FHAH/2Fplaylist.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==</Resource>
<RequestId>1712D6CE27FFE006</RequestId>
<HostId>7c380687-4104-4827-9aac-06084e6240a8</HostId>
</Error>

**Comment by shiyiya** [comment]
https://cdn.fshck.com/HAH/playlist.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==

**Comment by shiyiya** [comment]
not work

**Comment by shiyiya** [comment]
https://cdn.fshck.com/HAH/playlist.m3u8?demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==

**Comment by shiyiya** [comment]
> https://cdn.fshck.com/HAH/playlist.m3u8?demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==

await import('hls.js') working
await import('hls.js/dist/hls.light.min.js') do not working

@phpb-com

**Comment by shiyiya** [comment]
if u are using webpack
```ts
module.exports = {
  resolve: {
    alias: {
      'hls.js/dist/hls.light.min.js': 'hls.js',
    },
  },
}

// webpack v4
module.exports = {
  resolve: {
    alias: {
      'hls.js/dist/hls.light.min.js': 'hls.js',
    },
  },
}```

**Comment by NADESHIKON** [comment]
https://enime.moe/watch/vermeil-in-gold/10

I’m trying to play this video on iOS and it doesn’t load, strange.
Does this have to do with how oplayer lets iOS handle hls separateky

**Comment by NADESHIKON** [comment]
> HLs on iOS is handled natively, so just <video src='....m3u8' ...

oplayer already does that I think

**Comment by NADESHIKON** [comment]
> HLS.js is not supported on iPhone, no MSE extensions. So it is handled natively.

Yea but the problem is the native implementation does not load videos, you can try to access the link I posted with ios device

**Comment by shiyiya** [comment]
forceHls?

**Comment by NADESHIKON** [comment]
> I tried in simulator and it does not work, but you do have a bunch of hydration errors there:
> 
> ```
> [Error] Hydration completed but contains mismatches.
> 	u (entry-bda10fec.mjs:1:41024)
> 	mount (entry-bda10fec.mjs:1:39817)
> 	(anonymous function) (entry-bda10fec.mjs:13:206234)
> 	asyncFunctionResume
> 	(anonymous function)
> 	promiseReactionJobWithoutPromise
> [Error] Error: Invalid value for <svg> attribute width="1.5rem"
> 	Mu (entry-bda10fec.mjs:1:61777)
> 	Yu (entry-bda10fec.mjs:1:63642)
> 	D (entry-bda10fec.mjs:1:45177)
> 	N (entry-bda10fec.mjs:1:44810)
> 	S (entry-bda10fec.mjs:1:44240)
> 	H (entry-bda10fec.mjs:1:45774)
> 	D (entry-bda10fec.mjs:1:45054)
> 	N (entry-bda10fec.mjs:1:44810)
> 	S (entry-bda10fec.mjs:1:44240)
> 	H (entry-bda10fec.mjs:1:45774)
> 	D (entry-bda10fec.mjs:1:45054)
> 	N (entry-bda10fec.mjs:1:44810)
> 	S (entry-bda10fec.mjs:1:44240)
> 	H (entry-bda10fec.mjs:1:45774)
> 	D (entry-bda10fec.mjs:1:45054)
> 	N (entry-bda10fec.mjs:1:44810)
> 	S (entry-bda10fec.mjs:1:44240)
> 	H (entry-bda10fec.mjs:1:45774)
> 	D (entry-bda10fec.mjs:1:45054)
> 	N (entry-bda10fec.mjs:1:44810)
> 	S (entry-bda10fec.mjs:1:44240)
> 	R (entry-bda10fec.mjs:1:48507)
> 	run (entry-bda10fec.mjs:1:3877)
> 	ce (entry-bda10fec.mjs:1:48804)
> 	we (entry-bda10fec.mjs:1:47632)
> 	M (entry-bda10fec.mjs:1:47425)
> 	S (entry-bda10fec.mjs:1:44265)
> 	R (entry-bda10fec.mjs:1:48507)
> 	run (entry-bda10fec.mjs:1:3877)
> 	ce (entry-bda10fec.mjs:1:48804)
> 	(anonymous function) (entry-bda10fec.mjs:1:19700)
> 	promiseReactionJob
> ```

These might be due to ssr but they have nothing to do with how video is unable to play

**Comment by NADESHIKON** [comment]
> forceHls?

What’s forceHls

**Comment by NADESHIKON** [comment]
@shiyiya strange, iOS can play the sources that got changed from changeSource but for initial source it can’t play

**Comment by shiyiya** [comment]
Sorry, ignore that. I'm not sure what's going on at the moment. I'm reading your discussion.

**Comment by shiyiya** [comment]
Whether or not an issue needs to be reopened seems to be irrelevant to the current topic

**Comment by NADESHIKON** [comment]
Yes, I’ll open another issue

**Comment by shiyiya** [comment]
@phpb-com :+1:

**Comment by shiyiya** [comment]
@phpb-com I will set a better default behavior and not pass the configuration. Naming the configuration is a pain in the ass, (I'm not very good at naming configurations 🤯 ) if you have a lot of suggestions that would be great!

**Comment by NADESHIKON** [comment]
It should be ``qualityControl`` and ``qualitySwitchMode`` because it's inside the plugin so hls is assumed, and qualitySwitch should have "mode" after to be more clear

**Comment by NADESHIKON** [comment]
and it should be "immediate" and "smooth" for mode because next is rather confusing

**Comment by NADESHIKON** [comment]
> I thought of smooth too, but wanted to keep close to the HLS docs. Also, depending on how and where the config is passed, hls prefix should be dropped. Plugin already allows for usage of the native hls config (which I utilize for tuning), so there is that.

Ok then prefix is fine, but ``next`` is clearly more confusing than ``smooth`` so it's better to use that

**Comment by NADESHIKON** [comment]
Also, it should be possible to create a configuration that defines the strategy of default quality. For example, there can be an option that selects highest quality source by default

**Comment by NADESHIKON** [comment]
> This is already available via HLS settings: https://github.com/video-dev/hls.js/blob/master/docs/API.md#hlsloadlevel

We have to know what levels are available in order to use this option, since only -1 means auto and other levels have different IDs. Therefore the best way is for @shiyiya to add an option internally

**Comment by NADESHIKON** [comment]
> ```
> **capLevelController**
> (default: internal cap level controller)
> 
> Customized level capping controller.
> 
> A class in charge of setting hls.autoLevelCapping to limit ABR level selection based on player size. Enable the default cap level controller by setting capLevelToPlayerSize to true.
> ```

I see, but I still think making it a simple internal option will save a lot of work

**Comment by shiyiya** [comment]
@phpb-com https://discord.gg/hzjxYyPbkh

**Comment by shiyiya** [comment]
https://discord.gg/hzjxYyPbKh
@phpb-com

**Comment by shiyiya** [comment]
@phpb-com @NADESHIKON 

```ts
type hlsPluginOptions = {
  hlsConfig?: Partial<HlsConfig>
  matcher?: (video: HTMLVideoElement, source: Source) => boolean
  options?: {
    /**
     * @default: false
     */
    hlsQualityControl: boolean
    /**
     * @default: smooth
     */
    hlsQualitySwitch: 'immediate' | 'smooth' | undefined
  }
}
```

**Comment by shiyiya** [comment]
```ts
type hlsPluginOptions = {
  hlsConfig?: Partial<HlsConfig>
  matcher?: (video: HTMLVideoElement, source: Source) => boolean
  options?: {
    /**
     * @default: true
     */
    light: boolean //if hlsQualityControl= true, light must be false
    /**
     * @default: true
     */
    hlsQualityControl?: boolean
    /**
     * @default: smooth
     */
    hlsQualitySwitch?: 'immediate' | 'smooth'
  }
}
```

**Comment by shiyiya** [comment]
hlsQualityControl = true ==> light = true or false

**Comment by shiyiya** [comment]
light is about use `hls.js/dist/hls.light.min.js` or `hls.js/dist/hls.min.js`

**Comment by shiyiya** [comment]
if hlsQualityControl=false but want `hls.js/dist/hls.min.js`

**Comment by shiyiya** [comment]
At present, the settings menu does not have the function to actively set the selection items for the time being without consideration

**Comment by shiyiya** [comment]
could u run it in dev mode

**Comment by shiyiya** [comment]
But hls is not enabled on iOS, try hlsplugin once to see if it works

**Comment by shiyiya** [comment]
Based on the status above I can't tell why Try oplayer's site, it is also ssr

**Comment by shiyiya** [comment]
Based on the status above I can't tell why Try oplayer's site, it is also ssr

**Comment by shiyiya** [comment]
https://github.com/shiyiya/oplayer/commit/c5c5bd2a9592970dd16601b779ea6f465f5b7c25

**Comment by shiyiya** [comment]
Maybe this submission solves that problem

**Comment by shiyiya** [comment]
Keep it simple, you can actually just introduce it
https://github.com/shiyiya/oplayer/blob/main/website/src/components/Player.jsx#L1

**Comment by shiyiya** [comment]
yep

**Comment by shiyiya** [comment]
I will open pr with a big update


> Just checked the latest version 1.0.34, all seems to work as expected. May I suggest to do this type of discussions and testing in the Pull request, so we can test it with our setups and save you a lot of time and effort before it is merged and released? Thanks.

ok if there are more significant changes I will open pr

**Comment by shiyiya** [comment]
> Btw, I am not sure if setting the quality works on the paused/non-started video. Did you look into this already? --> [#18 (comment)](https://github.com/shiyiya/oplayer/issues/18#issuecomment-1241595872)

No, I'm not sure.

**Comment by shiyiya** [comment]
It has been tested and works well. https://github.com/shiyiya/oplayer/commit/706ab1f425028ef57086c580f18c2c084f133226#diff-873ea15f9df2b309f4d8078f1e958bfd9ec7fd708e354b50eee44121001b506dR74

However hlsjs doesn't seem to provide a way to set the current level externally? For example the highest quality is used by default, at the moment it's always the default unless you set it in the ui

**Comment by shiyiya** [comment]
This requires frequent modification of the settings menu

**Comment by shiyiya** [comment]
Of course, you can always launch pr 😄 

https://github.com/shiyiya/oplayer/blob/main/packages/ui/src/components/Setting.ts#L213
