### ISSUE TITLE
Videos played by this player are being blocked by adblocker 

### ISSUE THREAD

**Issue by NADESHIKON** [shiyiya/oplayer#19]
For example, uBlockOrigin blocks the video from this link https://enime.moe/watch/vermeil-in-gold/10 and it throws UNKNOWN_ERROR . However, other players like https://github.com/zhw2590582/ArtPlayer don't trigger the block with exactly same video link and HLS.

**Comment by shiyiya** [comment]
Please provide the error and try to print the error.

```ts
player.on((type, payload) => {
  if (type.indexOf('error')) {
    console.log(payload)
  }
})
```

**Comment by NADESHIKON** [comment]
> Please provide the error and try to print the error.
> 
> ```ts
> player.on((type, payload) => {
>   if (type.indexOf('error')) {
>     console.log(payload)
>   }
> })
> ```

I added logging to that page, it should log errors now. I don't know why but it looks like non-errors are also getting logged even there's ``type.indexOf('error')``

**Comment by shiyiya** [comment]
```ts
player.on(({type, payload}) => {
  if (type.indexOf('error')) {
    console.log(payload)
  }
})
```

**Comment by NADESHIKON** [comment]
> ```ts
> player.on(({type, payload}) => {
>   if (type.indexOf('error')) {
>     console.log(payload)
>   }
> })
> ```

I added this ``` player.on(({ type, payload }) => {
    if (type?.indexOf('error')) {
      console.log(payload)
    }
  })```

**Comment by NADESHIKON** [comment]
![image](https://user-images.githubusercontent.com/20222292/189044831-da20afe0-469f-4dc8-9c75-935e5b5e69ca.png)

This is the error

**Comment by NADESHIKON** [comment]
@shiyiya Update: I just realized oplayer sets default preload attribute to "auto" which some adlockers kinda hate it cuz it means ads. I changed it to ``metadata`` and it seems to no longer block.

**Comment by shiyiya** [comment]
🤯

**Comment by NADESHIKON** [comment]
> 🤯

I think it's better to make OPlayer default to metadata for preload to avoid further issues
