### ISSUE TITLE
Change source leads player display incorrect video length & subtitle not showing

### ISSUE THREAD

**Issue by NADESHIKON** [shiyiya/oplayer#20]
I'm currently trying to implement a "backup source" strategy which if the primary source somehow fails the player will try to load the video from a secondary source. What I have right now is like this:

```ts
player.on("error", async (event) => {
    if (event.payload.target?.error) {
      if (currentSourceIndex.value < props.sources.length) {
        currentSourceIndex.value++;
        source = props.sources[currentSourceIndex.value];

        let { data: sourceRef } = await useFetch(`${runtimeConfig.public.enimeApi}/source/${source.id}`, {
          key: `source-${source.id}`
        });

        await player.changeSource({
          src: sourceRef.value.url,
          poster: poster
        });

        if (sourceRef.value.subtitle) player.emit("subtitlechange", [{
          source: [
            {
              default: true,
              src: sourceRef.value.subtitle
            }
          ],
          fontSize: 30
        }] as Subtitle[]);
      }
}
```

However, it looks like after querying changeSource the player thinks video has more than 24 hours even it's only 24 minutes:
![image](https://user-images.githubusercontent.com/20222292/189057753-b4f61e85-393d-4c0e-9ca4-bf0c706443d7.png)

In addition, the subtitlechange is not really showing the subtitle, I don't see subtitle URL in the network tab either.

**Comment by shiyiya** [comment]
if (sourceRef.value.subtitle) player.emit("subtitlechange",  [
            {
              default: true,
              src: sourceRef.value.subtitle
            }
          ] as Subtitle[]);

**Comment by NADESHIKON** [comment]
> 

TS2352: Conversion of type '{ default: boolean; src: any; }[]' to type 'Subtitle[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.   Type '{ default: boolean; src: any; }' is not comparable to type 'Subtitle'.

**Comment by shiyiya** [comment]
```ts
if (sourceRef.value.subtitle) player.emit("subtitlechange", [
{
default: true,
src: sourceRef.value.subtitle
}
]);
```

**Comment by NADESHIKON** [comment]
> > 
> 
> TS2352: Conversion of type '{ default: boolean; src: any; }[]' to type 'Subtitle[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.   Type '{ default: boolean; src: any; }' is not comparable to type 'Subtitle'.

![image](https://user-images.githubusercontent.com/20222292/189060215-508afecc-9aa8-476e-b912-40859888181a.png)

The subtitle is still not there even I ignore the typescript error

**Comment by NADESHIKON** [comment]
https://cc.zorores.com/43/06/4306aee1a2793c4b9782c104797dd0f8/eng-2.vtt

This is the file btw

**Comment by NADESHIKON** [comment]
@shiyiya There's also issues with video length other than subtitle, did that get fixed in the latest commit since I only saw you fixed subtitle part

**Comment by shiyiya** [comment]
> @shiyiya There's also issues with video length besides subtitle, did that get fixed in the latest commit since I only saw you fixed subtitle part

please provide 2 url

**Comment by NADESHIKON** [comment]
> > @shiyiya There's also issues with video length besides subtitle, did that get fixed in the latest commit since I only saw you fixed subtitle part
> 
> please provide 2 url

Nevermind, it looks like it's hls.js issue and updating hls.js fixed it
