### ISSUE TITLE
iOS is unable to load videos from initial source

### ISSUE THREAD

**Issue by NADESHIKON** [shiyiya/oplayer#21]
https://enime.moe/watch/my-stepmom's-daughter-is-my-ex/10

However, with changeSource (for backup sources) the videos can be properly loaded.

**Comment by shiyiya** [comment]
#18

**Comment by NADESHIKON** [comment]
> I tried to load https://cache.387e6278d8e06083d813358762e0ac63.com/222869752030.m3u8 in the simulator on the main brunch build of oplayer and it worked. It definitely breaks in the simulator and iPhone. Going to full screen also does not help, but can scrub through the timeline, with no playing.
> 
> I suspect that something is wrong with your oplayer config. Hls.js should not play any role on iPhone, since it exits as soon as this code is hit:
> 
> ```ts
>       if (!HLS.isSupported()) {
>         emit('pluginerror', {
>           payload: {
>             type: 'hlsNotSupported',
>             message: 'hlsNotSupported'
>           }
>         })
>         return true
>       }
> ```

I doubt my configuration is wrong, you can check it here https://github.com/Enime-Project/enime.moe/blob/4541f3154700353edff1c34920fa607f1390d53b/components/player/index.vue#L54

**Comment by NADESHIKON** [comment]
For 404 it’s json but when it’s 200 it returns right m3u8

**Comment by NADESHIKON** [comment]
> Have you tried running it with 1.0.30 of oplayer? is it only broken on 1.0.32/31?

Never tried on 1.0.30 but it looks like hls.js is still getting triggered with ios devices for initial source only. For sources that got changed after changeSource method ios handles them nativeky

**Comment by shiyiya** [comment]
> I tried to load https://cache.387e6278d8e06083d813358762e0ac63.com/222869752030.m3u8 in the simulator on the main brunch build of oplayer and it worked. It definitely breaks in the simulator and iPhone. Going to full screen also does not help, but can scrub through the timeline, with no playing.
> 
> I suspect that something is wrong with your oplayer config. Hls.js should not play any role on iPhone, since it exits as soon as this code is hit:
> 
> ```ts
>       if (!HLS.isSupported()) {
>         emit('pluginerror', {
>           payload: {
>             type: 'hlsNotSupported',
>             message: 'hlsNotSupported'
>           }
>         })
>         return true
>       }
> ```

Should false be returned here? lol

**Comment by shiyiya** [comment]
Returning true will not set the video's src

**Comment by shiyiya** [comment]
Then error should not be needed

**Comment by NADESHIKON** [comment]
> https://github.com/shiyiya/oplayer/blob/1831c96caf2530b9deebfc88d44b7e677956d9be/packages/core/src/player.ts#L187
> 
> This should probably be looked into, is it correct to 'break' in this case, not return?

Wait.. if you break here then the video src is never set because you returned true and src is only set if customLoader is false

**Comment by shiyiya** [comment]
🔢

**Comment by shiyiya** [comment]
I will release a new version to confirm that there are no problems.
