### ISSUE TITLE
Support VTT sprite for thumbnail

### ISSUE THREAD

**Issue by NADESHIKON** [shiyiya/oplayer#22]
For example: https://preview.zorores.com/4b/4b1a02c7ffcad4f1ee11cd6f474548cb/thumbnails/sprite.vtt

There's a videojs plugin for such implementation: https://github.com/chrisboustead/videojs-vtt-thumbnails/blob/master/src/plugin.js

**Comment by shiyiya** [comment]
Done.

https://github.com/shiyiya/oplayer/commit/a96245d8f6c5f3daa28e3f9504c11bbf04922e36

**Comment by shiyiya** [comment]
> Wow, that was fast. I just left one comment about the URL that you have in the code for the CSS background. It seems to be out of place.

fixd

**Comment by shiyiya** [comment]
> For example: https://preview.zorores.com/4b/4b1a02c7ffcad4f1ee11cd6f474548cb/thumbnails/sprite.vtt
> 
work on it

**Comment by shiyiya** [comment]
> 

now, no `base`

**Comment by shiyiya** [comment]
https://oplayer.vercel.app/playground?code=import%20Player,%20{%20isMobile,%20isiPad,%20isiPhone,%20isIOS%20}%20from%20%27/core.es.js%27%20import%20ui%20from%20%27/ui.es.js%27%20import%20danmaku%20from%20%27/danmaku.es.js%27%20import%20hls%20from%20%27/hls.es.js%27%20import%20dash%20from%20%27/dash.es.js%27%20Player.make(document.getElementById(%27oplayer%27),%20{%20source:%20{%20src:%20%27https://oplayer.vercel.app/%E5%90%9B%E3%81%AE%E5%90%8D%E3%81%AF.mp4%27,%20poster:%20%27https://oplayer.vercel.app/poster.png%27%20}%20})%20.use([%20ui({%20thumbnails:%20{%20src:%20%27https://preview.zorores.com/4b/4b1a02c7ffcad4f1ee11cd6f474548cb/thumbnails/sprite.vtt%27,%20isVTT:%20true,%20number:%20100%20}%20})%20])%20.create()

**Comment by shiyiya** [comment]
done
