### ISSUE TITLE
React package does not work with React SSR

### ISSUE THREAD

**Issue by phpb-com** [shiyiya/oplayer#4]
Hi, I have tried to use oplayer with Remix and could not start the server due to a lot of errors. It seems that the server-side code is trying to access window.document which does not exist. If you want me to provide you with the reproduction case, I can make a sample repo.

**Comment by shiyiya** [comment]
Currently, SSR is not supported.

This is my current solution.

https://github.com/shiyiya/oplayer/blob/main/website/src/pages/components/Playground/index.jsx#L8

**Comment by shiyiya** [comment]
This may take some time.
Of course, if you are willing to help, welcome PR.
Thanks.

**Comment by shiyiya** [comment]
Updated f611402d0a2898a368d04c2cb03dd4afa65db1d8

Try v1.0.20

https://github.com/shiyiya/oplayer/blob/main/website/src/components/Playground/index.jsx#L8
