### ISSUE TITLE
Please help me with cdn libraries

### ISSUE THREAD

**Issue by scara78** [shiyiya/oplayer#45]
<html>
<body>

<script src="https://cdn.jsdelivr.net/npm/@oplayer/core@latest/dist/index.min.js"></script>
--
  | <script src="https://cdn.jsdelivr.net/npm/@oplayer/ui@latest/dist/index.min.js"></script>
  | <script src="https://cdn.jsdelivr.net/npm/@oplayer/hls@latest/dist/index.min.js"></script>
  |  
  | <div id="oplayer" />
  |  
  | <script>
  | OPlayer.make(document.getElementById('oplayer'), {
  | source: {
  | src: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  | poster: 'https://oplayer.vercel.app/poster.png'
  | }
  | })
  |  
  |  
  |  
  | .use([
  | OUI({
  | menu: [
  | {
  | name: 'source',
  | children: [
  | {
  | name: 'Server1',
  | default: true,
  | value: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  | },
  | {
  | name: 'hls',
  | value: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  | },
  | {
  | name: 'Server3',
  | value: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  | },
  | ],
  | onChange({ value }) {
  | player.changeSource({ src: value })
  | }
  | }
  | ]
  | }),
  | OHls()
  | ])
  | .create();
  | </script>
  | </body>
  | </html>

</body>
</html>

What is wrong in my code, the player works only with mp4, on hls media is not supported.
Also, the media source is not changing on switch.
Please help me with correct code.
Thanks in advance

**Comment by shiyiya** [comment]
u need import hls.js

**Comment by shiyiya** [comment]
https://cdn.jsdelivr.net/npm/hls.js@1.2.4/dist/hls.min.js

@scara78

```html
<script src="https://cdn.jsdelivr.net/npm/@oplayer/core@latest/dist/index.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@oplayer/ui@latest/dist/index.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/hls.js@1.2.4/dist/hls.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@oplayer/hls@latest/dist/index.min.js"></script>

<script>
  OPlayer.make(document.getElementById('oplayer'), {
    source: {
      src: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
      poster: 'https://oplayer.vercel.app/poster.png',
    },
  })

    .use([
      OUI({
        menu: [
          {
            name: 'source',
            children: [
              {
                name: 'Server1',
                default: true,
                value: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
              },
              {
                name: 'hls',
                value: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
              },
              {
                name: 'Server3',
                value: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
              },
            ],
            onChange({ value }) {
              player.changeSource({ src: value })
            },
          },
        ],
      }),
      OHls(),
    ])
    .create()
</script>
```

**Comment by scara78** [comment]
Uncaught ReferenceError: player is not defined
    at Object.onChange (rp.php?id=tt11851548:53:15)
    at HTMLDivElement.<anonymous> (index.ts:69:65)

its still not changing source, i got this error on developer tool
Thanks for help!

**Comment by shiyiya** [comment]
code updated https://github.com/shiyiya/oplayer/issues/45#issuecomment-1302897559

**Comment by scara78** [comment]
works fine now, thank allot!
Still have one issue, on souce changing - the subtitle track are gone, i will have to refresh the player to bring him back.

**Comment by shiyiya** [comment]
upgrade oplayer version.

use `player.changeQuality(src)`

**Comment by shiyiya** [comment]
If there are still problems, you can reopen this issue.
