### ISSUE TITLE
Qualities not showing on mobile

### ISSUE THREAD

**Issue by casualGamer-dev** [shiyiya/oplayer#54]

**Comment by shiyiya** [comment]
Quality control is provided by hls.js
It won't work on ios. iOS uses built-in decoder instead of MSE

are u ios ?

**Comment by shiyiya** [comment]
Need to provide more information.

## Environment

- oplayer/core:   // version
- oplayer/ui:       // version
- oplayer/hls:    // version
- platform:          // IOS 11, Android 13, etc.
- browser:           // chrome 108.0.5359.124, etc.

**Comment by casualGamer-dev** [comment]
"@oplayer/core": "^1.2.9",
    "@oplayer/hls": "^1.2.6",
    "@oplayer/ui": "^1.2.10",
    platform : android 
    Browser : chrome

**Comment by casualGamer-dev** [comment]
opening site from mobile doesnt not show the option to change quality
u can test it out yourself https://gojo.tv

**Comment by shiyiya** [comment]
You can try to update to the latest version.

**Comment by shiyiya** [comment]
https://gojo.tv/watch/140596?episode=ijiranaide-nagatoro-san-2nd-attack-episode-2&provider=gogoanime

https://web.xn--7ov117aclgs4c.life/v/don't-toy-with-me-miss-nagatoro-2nd-attack

**Comment by shiyiya** [comment]
@casualGamer-dev 

Maybe I have found the answer.
When the browser supports the corresponding video format, the corresponding plug-in will not be loaded. For example, if iOS built-in supports playing m3u8, the `hls.js` will not be loaded. Now that Chrome Mobile also supports m3u8, `hls.js` will not be used by default, so the quality switch will also fail.

You can try to force the use of `hls.js`
```js
hls({ matcher: () => true })
```

**Comment by shiyiya** [comment]
Now `player.$video.canPlayType('application/x-mpegURL') ` returned 'maybe'.

chrome mobile 108.0.5359128

**Comment by shiyiya** [comment]
https://deploy-preview-4--animehi-stream.netlify.app/watch/146346?episode=cldd9jbpa000gz0pk52cecx1r&provider=gogoanime

It' work.
