### ISSUE TITLE
Change player width & height when/after container size changed

### ISSUE THREAD

**Issue by leopku** [shiyiya/oplayer#55]
## 🚀 Feature Proposal

Change player width & height when/after container size changed

## Motivation

When container size changed smaller, player size keep no change.

## Example

Please provide an example for how this feature would be used.

## Pitch

Why does this feature belong in the oplayer ecosystem?

**Comment by shiyiya** [comment]
Just one line of css is all it takes.

```css
aspect-ratio: 16/9; // Any ratio you want
```

**Comment by leopku** [comment]
Sorry, I didn't describe my problem clearly.

I'm using react component `@oplayer/react`.

After the react player component rendered, the player won't change it's size while container changed.
There wasn't problem about aspect ratio.

Any advice?

**Comment by shiyiya** [comment]
The player will fill the container. You just need to set the width and height of the container, and the size of the player will change with the container.

Maybe I don't know what you want. You can use pictures to describe the current situation and expectations

**Comment by leopku** [comment]
1、播放器有办法自适应 container 大小没？

截图是在一个弹出的新窗口中，留意截图下面的空白部分。

https://imgur.com/a/e1q53dG

2、手动调整弹出窗口的大小，播放器大小不会自动调整。有没有类似 changeSize(width, heigh) 这样方法，在窗口的大小变更回调中可以调用。

PS：oplayer 这样的插件式设计个人非常喜欢，目前在试验从 nplayer 切到 oplayer

**Comment by shiyiya** [comment]
传递 aspect-ratio 为 0 试试

**Comment by leopku** [comment]
不行，设了 aspectRatio={0} 后白屏了，控制台没有报错。

```jsx
    <ReactPlayer
      plugins={plugins}
      aspectRatio={0}
      ref={player}
      autoplay={true}
      source={source}
    />
```

**Comment by shiyiya** [comment]
😂 你把 react 复制出来，去掉aspectRatio那部分，只留ref那层就好了, 或者等晚点我改一下

**Comment by leopku** [comment]
试了一下，还是不行。等你改吧。谢了先。

**Comment by shiyiya** [comment]
v 1.2.5 released.

```jsx
 <ReactPlayer
      plugins={plugins}
      aspectRatio={0}
      ref={player}
      autoplay={true}
      source={source}
    />
```

**Comment by leopku** [comment]
Perfect. It fixed.
Thanks a lot.

**Comment by leopku** [comment]
@shiyiya 全新项目，`aspectRatio` 不起作用了？

**Comment by shiyiya** [comment]
aspectRatio 0?

**Comment by leopku** [comment]
奇怪了，我这新窗口弹出后，没有随 container 改变大小

**Comment by shiyiya** [comment]
> 奇怪了，我这新窗口弹出后，没有随 container 改变大小

被其他样式影响了吧

**Comment by leopku** [comment]
> > 奇怪了，我这新窗口弹出后，没有随 container 改变大小
> 
> 被其他样式影响了吧

应该不是。两处代码一样。

我再查查
