### ISSUE TITLE
HLS playback does not work on the iPhone if autoplay is not set to true.

### ISSUE THREAD

**Issue by phpb-com** [shiyiya/oplayer#7]
Found one bug, HLS playback does not work on the iPhone. Setting autoplay to true, makes the player work as expected on the iPhone.

_Originally posted by @phpb-com in https://github.com/shiyiya/oplayer/issues/4#issuecomment-1225701501_

**Comment by shiyiya** [comment]
This may be a hls.js issue.

**Comment by shiyiya** [comment]
I don't get what you mean, let's sort it out.

### with hlsjs

autoplay : true -> not work
autoplay: false -> not work

### no hlsjs

autoplay : true -> work
autoplay ：false -> work

Is this what you mean?

**Comment by shiyiya** [comment]
native suporrt HLS | autoplay | no autoplay
-- | -- | --
Chrome | N | Y | N*
Safari | Y | Y* | Y*
Firefox | N | Y | Y

**Comment by shiyiya** [comment]
- If you want the video to play automatically, you need to set it to mute `mute: true`.
- If or not there are throwing errors

**Comment by shiyiya** [comment]
- This is a autoplay example work on macsafari, macchorme, android chrome.
https://github.com/shiyiya/oplayer/blob/0a7914087ee2fc1bb5b19aa77c19e4671823d43f/examples/standalone/main.ts#L55

**Comment by shiyiya** [comment]
Customize match to not use hls.js on IOS.
Will this work?
```ts
hlsPlugin({
  matcher: () => (isIOS ? false : source.format === 'm3u8' || /m3u8(#|\?|$)/i.test(source.src))
})
```

**Comment by shiyiya** [comment]
Ok. I got it.

**Comment by shiyiya** [comment]
The video duration is loaded but cannot be played by clicking on it, probably because the UI is obscured by other elements.
