### ISSUE TITLE
Playback pauses when exiting a full screen mode on iPhone

### ISSUE THREAD

**Issue by phpb-com** [shiyiya/oplayer#8]
After you implementation of the native fullscreen mode for iPhone, all works as expected but the exit from the fullscreen mode. The playback pauses and have to be restarted manually.

**Comment by shiyiya** [comment]
ios No fullscreen events, I can't know the current state and make changes

**Comment by shiyiya** [comment]
![image](https://user-images.githubusercontent.com/34017352/186659174-2817a722-f40e-4797-b1b1-80614bc037d2.png)

lol
