### ISSUE TITLE
How to add custom icon in  it.

### ISSUE THREAD

**Issue by MuhammadTufailAli** [shiyiya/oplayer#80]
In documentation it is said that to add custom icon do following
{
  icons: {
    play: '',
    pause: '',
    volume: ['', ''], //on off
    fullscreen: ['', ''], //on off
    pip: '',
    setting: '',
    screenshot: '',
    playbackRate: '',
    loop: '',
    progressIndicator: '',
    loadingIndicator: ''
  }
}
But it only accepts string, in documentation it is not specified how to use your custom svg or png has icon or how can we use react icon instead of oplayer default icons> Can you please help me about this issue.

**Comment by shiyiya** [comment]
Sorry, there is no support for using react-component, only for using HTML Dom string, which you can interpret as a dom created using innerHTML. you can copy the svg after your react render

**Comment by shiyiya** [comment]
https://github.com/shiyiya/oplayer/blob/97b352ae6ac9d0c99c81b9440f55a2571d11f578/examples/standalone/main.ts#L73
