### ISSUE TITLE
Is there any option in oplayer to set back button at top of the media playe

### ISSUE THREAD

**Issue by MuhammadTufailAli** [shiyiya/oplayer#81]
Can you please tell me is there any custom option to enable back button on top of media player as i was not ablt to find it in documentation. Please help

**Comment by shiyiya** [comment]
controlBar: { back: 'always' },

**Comment by shiyiya** [comment]
https://github.com/shiyiya/oplayer/blob/97b352ae6ac9d0c99c81b9440f55a2571d11f578/examples/standalone/main.ts#L57 
make controllbar be true first
