### ISSUE TITLE
I need migrate from old player to oPlayer

### ISSUE THREAD

**Issue by namdevel** [shiyiya/oplayer#84]
## 💬 Questions and Help

How to use in nuxt JS ?

**Comment by shiyiya** [comment]
just write `player.make` in `onMounted`

**Comment by shiyiya** [comment]
No response, close

**Comment by namdevel** [comment]
i'm confised, can you help me ?

**Comment by namdevel** [comment]
because i just new learn vuejs

**Comment by shiyiya** [comment]
np 😄

**Comment by namdevel** [comment]
do you have discord ?

**Comment by namdevel** [comment]
hello, please accept my invitation colaborator

**Comment by shiyiya** [comment]
> do you have discord ?

readme has discord invitation link
