### ISSUE TITLE
When subtitle default is true it does not show

### ISSUE THREAD

**Issue by MuhammadTufailAli** [shiyiya/oplayer#96]
I am using subtitle in Oplayer.
Following is my code
 .use(
            [
              ui({
                theme: { primaryColor: "#D98420" },
                coverButton: true,
                pictureInPicture: false,
                miniProgressBar: false,

                controlBar: false, //chrome cast ko uper la k jana k lia
                //subtitle are added
                subtitle: {
                  color: "white",
                  fontSize: 24,
                  fontWeight: 700,
                  fontFamily: "Roboto",
                  background: true,
                  source: [
                    {
                      name: "English",
                      default: true,
                      src: MediaToPlay?.srt_file,
                    },
                  ],
                },

    
              hls({ forceHLS: true }),

              // chromecast,
              conditionToChromeCast && otherBrowser && chromecast,
            ].filter(Boolean)
          )
          
          When subtitle    default: true, then it does not show but if i do    default: false and then enable it manually subtitle starts showing. Please help me resolve this issue

**Comment by MuhammadTufailAli** [comment]
i console my Oplayer when it was created 
My currentSubtitle is 
{
    "name": "English",
    "default": true,
    "src": "https://streambe1.nayatel.com/movies/Navalny.1080p-HD.srt"
}
but 
isShow:false

If i reload page then isShow gets true why is this behaviour

**Comment by shiyiya** [comment]
pls upload srt file

**Comment by MuhammadTufailAli** [comment]
Upload srt file where i don't understand what you said. Can you please explain?

**Comment by MuhammadTufailAli** [comment]
I also added my movie link and srt link in Oplayer playground it is also not showing over there

My code
const player = Player.make("#app", {
  // isLive: true,
  source: {
    src: "https://5c7da495a96a8.streamlock.net/vodedge/_definst_/http/movies/Navalny.1080p-HD.mp4/playlist.m3u8",
    poster: "https://ohplayer.netlify.app/poster.png",
    title: "君の名は"
  },
  autoplay: true,
  videoAttr: {
    // crossOrigin: "anonymous"
  }
})
  .use([
    ui({
      subtitle: {
        background: true,
        source: [
          {
            name: "Japanese",
            default: true,
            src: "https://streambe1.nayatel.com/movies/Navalny.1080p-HD.srt"

          },
          {
            name: "CH & JP",
            src: "https://ohplayer.netlify.app/君の名は.srt"
          }
        ]
      },
      
     If i reload then subtitles starts showing and if i make subtitle default:false and manually open it then its start showing

**Comment by shiyiya** [comment]
source cannot access

**Comment by MuhammadTufailAli** [comment]
So what should i do

**Comment by MuhammadTufailAli** [comment]
i also added Oplayer playground src
{
            name: "Japanese",
            default: true,
            src: "https://ohplayer.netlify.app/君の名は-jp.srt"
          }
          
          But it is also now showing if default: true,

**Comment by MuhammadTufailAli** [comment]
Please give me solution

**Comment by shiyiya** [comment]
https://oplayer.vercel.app/preview/
is ok？

**Comment by MuhammadTufailAli** [comment]
Yes above is working fine but in my case subtitle are not showing
Can you please use movie src as
https://5c7da495a96a8.streamlock.net/vodedge/_definst_/http/movies/Navalny.1080p-HD.mp4/playlist.m3u8
and use  following subtitle 
https://streambe1.nayatel.com/movies/Navalny.1080p-HD.srt
and check if subtitle show or not
In this way we will check where problem exists?

**Comment by shiyiya** [comment]
Unable to access your resources and subtitle files

**Comment by shiyiya** [comment]
No time this week, looking at it next week, provide your srt file

**Comment by eritpchy** [comment]
Same issue on @oplayer/ui": "1.2.34-beta.1 & Chrome 117.0.5938.149 (Official Build) (x86_64)

**Comment by shiyiya** [comment]
> Same issue on @oplayer/ui": "1.2.34-beta.1 & Chrome 117.0.5938.149 (Official Build) (x86_64)

reproduction repo？

**Comment by eritpchy** [comment]
> > Same issue on @oplayer/ui": "1.2.34-beta.1 & Chrome 117.0.5938.149 (Official Build) (x86_64)
> 
> reproduction repo？

Not yet. but I just got workaround this problem.
![image](https://github.com/shiyiya/oplayer/assets/8630635/b20ad856-7eac-4348-8f8b-da77ce8235a4)

**Comment by shiyiya** [comment]
> > > Same issue on @oplayer/ui": "1.2.34-beta.1 & Chrome 117.0.5938.149 (Official Build) (x86_64)
> > 
> > 
> > reproduction repo？
> 
> Not yet. but I just got workaround this problem. ![image](https://user-images.githubusercontent.com/8630635/275304791-b20ad856-7eac-4348-8f8b-da77ce8235a4.png)

所以只是写法错了。

**Comment by eritpchy** [comment]
<img width="470" alt="image" src="https://github.com/shiyiya/oplayer/assets/8630635/bf483346-f62b-4dbf-9bcb-25d9126ebf89">


差不多, 我感觉和这个src 有关系

<img width="578" alt="image" src="https://github.com/shiyiya/oplayer/assets/8630635/2f08fc2a-5a8d-4429-ab82-258b321e9d96">


很奇怪, 如果用之前的写法刚刷新页面进去第一次是ok的, 然后重新加载oplayer就挂了


<img width="595" alt="image" src="https://github.com/shiyiya/oplayer/assets/8630635/94b77b0a-1213-4b38-abea-63bf8dd53571">

这两cues都没了

**Comment by shiyiya** [comment]
切换视频源会重建cue

**Comment by MuhammadTufailAli** [comment]
I am using subtitle in Oplayer.
Following is my code
.use(
[
ui({
theme: { primaryColor: "#D98420" },
coverButton: true,
pictureInPicture: false,
miniProgressBar: false,

            controlBar: false, //chrome cast ko uper la k jana k lia
            //subtitle are added
            subtitle: {
              color: "white",
              fontSize: 24,
              fontWeight: 700,
              fontFamily: "Roboto",
              background: true,
              source: [
                {
                  name: "English",
                  default: true,
                  src: MediaToPlay?.srt_file,
                },
              ],
            },


          hls({ forceHLS: true }),

          // chromecast,
          conditionToChromeCast && otherBrowser && chromecast,
        ].filter(Boolean)
      )
      
      When subtitle    default: true, then it does not show but if i do    default: false and then enable it manually subtitle starts showing. Please help me resolve this issue

**Comment by eritpchy** [comment]
我代码是放在vue的onMounted 里面的, 重新加载大概就是...关了vue这个页面,再打开.

```javascript
onMounted(() => {
  emit('load');
  const player = Player.make('#oplayer', {
    source: {
      poster: webdav_thumbnail_link(props.selection.item),
      title: props.selection.item.basename,
    }
  }).use([
    ui({
      controlBar: { back: "always" },
      fullscreen: true,
    }),
    hls({
      forceHLS: true,
      withBitrate: true,
      active(instance, lib) {
        instance.on(lib.Events.MANIFEST_PARSED, (...payload) => {
          console.log(payload);
        });
      }
    }),
    dash({
      withBitrate: true,
      active(instance, lib) {
        instance.on("streamInitialized", (payload) => {
          console.log(payload);
        });
      }
    }),
    mpegts(),
  ]).create()

  fetch(...).then(() => {
    player.changeSource({
       src: videoUrlList[0].value,
       poster: webdav_thumbnail_link(props.selection.item),
       title: props.selection.item.basename,
    })
    player.context.ui.subtitle.changeSource(subtitleUrlList)
  })
})
```

**Comment by MuhammadTufailAli** [comment]
![subtitle](https://github.com/shiyiya/oplayer/assets/80455451/98104196-f702-49ca-8054-6621df3608de)

Look Even i used default: true, but when player is made the subtitle does not show and in console isShow is false

**Comment by MuhammadTufailAli** [comment]
If i reload this page then isSHow get true and also if i do default: false and then manually turn on sutitle it works fine

**Comment by shiyiya** [comment]
@eritpchy 关页面重新拿不应该啊

**Comment by eritpchy** [comment]
> MediaToPlay?.srt_file
Try this. type: 'srt'

```javascript
{
  name: "English",
  default: true,
  src: MediaToPlay?.srt_file,
  type: 'srt',
},
```

**Comment by eritpchy** [comment]
> @eritpchy 关页面重新拿不应该啊

哈哈哈, 可能就是加载视频然后再加载字幕太快了导致的吧

**Comment by eritpchy** [comment]
> @eritpchy changeshource -》 changesubtitle

我搜索了下代码, 没有changesubtitle这个方法吧

**Comment by MuhammadTufailAli** [comment]
@eritpchy  i also tried to do this but still in console i get isShow:false why this wired behavior?

**Comment by MuhammadTufailAli** [comment]
"@oplayer/ui": "^1.2.32",
 My ui version

**Comment by eritpchy** [comment]
> "@oplayer/ui": "^1.2.32", My ui version

Maybe you should upgrade to @oplayer/ui": "1.2.34-beta.1 ?

**Comment by MuhammadTufailAli** [comment]
Is it working fine in 1.2.34?

**Comment by eritpchy** [comment]
Not sure..

**Comment by MuhammadTufailAli** [comment]
@shiyiya ????

**Comment by eritpchy** [comment]
<img width="977" alt="image" src="https://github.com/shiyiya/oplayer/assets/8630635/85c639f7-94c4-42e8-a4ec-892a45d2a6b1">

@MuhammadTufailAli

**Comment by shiyiya** [comment]
Are you using oplayer, may i put it in oplayer readme?
## Who use OPlayer?

- [NGEWIBU.TV](https://ngewibu.tv/) : Nonton Anime Sub Indo | Nonton Anime Subtitle Indonesia Gratis
- [Animex](https://www.animex.live/) : Watch Anime for free in HD quality with English subbed or dubbed.
- [UPV](https://onime.netlify.app) : free animes no ad
- **Feel free to submit yours in [Let me know!](https://github.com/shiyiya/oplayer/discussions/new?category=show-and-tell)**

**Comment by eritpchy** [comment]
@shiyiya  还没发布, 且太小众, 都不好意思了😅

**Comment by shiyiya** [comment]
> @shiyiya 还没发布, 且太小众, 都不好意思了😅

那就点个star先 🤣

**Comment by shiyiya** [comment]
> "@oplayer/ui": "^1.2.32", My ui version

try upgrade all oplayer

```shell
npm update @oplayer/core @oplayer/ui @oplayer/xxx
```

**Comment by MuhammadTufailAli** [comment]
Okay i hope nothing will crash after that 🤣

**Comment by MuhammadTufailAli** [comment]
i updated my Oplayer all dependencies now my "@oplayer/ui": "^1.2.32", But still subtitle is not showing. Still isShow is false. Why it is still not resolved

**Comment by shiyiya** [comment]
close，no respond

**Comment by eritpchy** [comment]
> Are you using oplayer, may i put it in oplayer readme?
> 
> ## Who use OPlayer?
> * [NGEWIBU.TV](https://ngewibu.tv/) : Nonton Anime Sub Indo | Nonton Anime Subtitle Indonesia Gratis
> * [Animex](https://www.animex.live/) : Watch Anime for free in HD quality with English subbed or dubbed.
> * [UPV](https://onime.netlify.app) : free animes no ad
> * **Feel free to submit yours in [Let me know!](https://github.com/shiyiya/oplayer/discussions/new?category=show-and-tell)**

https://github.com/eritpchy/aliyundrive-webdav/releases
已经发布, 用了你的oplayer😃
