### ISSUE TITLE
When i play live stream and click on next epiosode i still receive chunks of previous channel

### ISSUE THREAD

**Issue by MuhammadTufailAli** [shiyiya/oplayer#97]
I am using Oplay for live channel stream I have playlist of channels 
i created custom button for next channel and previous channel everytime i click next button i detroy media player and then create new one.
button are working fine but when i change channel i still receive chunks of last channel in network tab of browser inspect element
i also used default button offered by oplayer for next and previous but i encountred same issue here also

**Comment by shiyiya** [comment]
![image](https://github.com/shiyiya/oplayer/assets/34017352/02f6990f-68c7-445b-b999-a3b08564e93a)
