### ISSUE TITLE
 The drop-down menu will not automatically disappear after clicking on the mobile phone

### ISSUE THREAD

**Issue by eritpchy** [shiyiya/oplayer#99]
## Environment

- oplayer/core@1.2.31:
- oplayer/ui@1.2.34-beta.1
- oplayer/hls@1.2.23
- oplayer/dash@1.2.23
- platform: macOS
- browser:  Chrome 117.0.5938.149 (Official Build) (x86_64) (Open dev tools, select mobile view)

## 🐛 Bug Report

 The drop-down menu will not automatically disappear after clicking on the mobile phone, but this will not happen on the desktop version.

## To Reproduce

https://github.com/shiyiya/oplayer/assets/8630635/e0c4df73-72a8-459a-aa59-4a341044099e

## Expected behavior

https://github.com/shiyiya/oplayer/assets/8630635/0ee475db-ef7a-4a0b-9776-9b8386a5d16e

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

**Comment by shiyiya** [comment]
putting it in the settings
